-- 部署テーブル
CREATE TABLE DEPARTMENT (
DEPARTMENT_ID   INT PRIMARY KEY,      -- 部署ID
DEPARTMENT_NAME VARCHAR(30) NOT NULL, -- 部署名
LOCATION        VARCHAR(30) NOT NULL  -- 所在地
);

-- 社員テーブル
CREATE TABLE EMPLOYEE (
EMPLOYEE_ID   INT PRIMARY KEY,      -- 社員ID
EMPLOYEE_NAME VARCHAR(30) NOT NULL, -- 社員名
DEPARTMENT_ID INT,                   -- 部署ID
EMPLOYEE_TYPE CHAR NOT NULL,        -- 社員種別
ENTRANCE_DATE DATE NOT NULL,        -- 入社年月日
JOB_ID        INT NOT NULL,         -- 役職ID
SALARY        INT,                   -- 月給（社員）
WAGE          INT,                   -- 時給（パート）
CONSTRAINT FK_DEPARTMENT FOREIGN KEY(DEPARTMENT_ID)
    REFERENCES DEPARTMENT(DEPARTMENT_ID)
);
