-- 一括ドロップ
DROP TABLE IF EXISTS FILE_STORE;

CREATE TABLE FILE_STORE (
FILE_ID      INT AUTO_INCREMENT,    -- ファイルID
FILE_NAME    VARCHAR(200) NOT NULL, -- ファイル名
CONTENT_TYPE VARCHAR(50) NOT NULL,  -- コンテントタイプ
FILE         MEDIUMBLOB NOT NULL,   -- ファイル
PRIMARY KEY (FILE_ID)
);
