CREATE USER 'TESTUSER' IDENTIFIED BY 'PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO 'TESTUSER'@'%' IDENTIFIED BY 'PASSWORD';

CREATE USER 'USER_C' IDENTIFIED BY 'PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO 'USER_C'@'%' IDENTIFIED BY 'PASSWORD';

CREATE USER 'USER_S' IDENTIFIED BY 'PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO 'USER_S'@'%' IDENTIFIED BY 'PASSWORD';
