DELETE FROM HISTORICAL_SALES_BY_CUSTOMER;
DELETE FROM HISTORICAL_SALES_BY_PRODUCT_TYPE;
DELETE FROM HISTORICAL_SALES_BY_PRODUCT;
DELETE FROM SALES_AMOUNT_BY_CUSTOMER;
DELETE FROM SALES_AMOUNT_BY_BRANCH;
DELETE FROM SALES_DETAIL;
DELETE FROM SALES_TRAN;
DELETE FROM CUSTOMER;
DELETE FROM STAFF;
DELETE FROM BRANCH;
DELETE FROM STOCK_PRODUCT;
DELETE FROM PRODUCT_NEW_PRICE;
DELETE FROM PRODUCT;
DELETE FROM PRODUCT_TYPE;

