-- 一括ドロップ
DROP TABLE IF EXISTS EMPLOYEE_QUALIFICATION;
DROP TABLE IF EXISTS EMPLOYEE_PROJECT;
DROP TABLE IF EXISTS EMAIL;
DROP TABLE IF EXISTS PHONE;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS FULLTIMER;
DROP TABLE IF EXISTS PARTTIMER;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS JOB;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS QUALIFICATION;
DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS GENERATED_ID;