-- 一括ドロップ
DROP TABLE EMPLOYEE_QUALIFICATION;
DROP TABLE EMPLOYEE_PROJECT;
DROP TABLE EMAIL;
DROP TABLE PHONE;
DROP TABLE EMPLOYEE;
DROP TABLE FULLTIMER;
DROP TABLE PARTTIMER;
DROP TABLE DEPARTMENT;
DROP TABLE JOB;
DROP TABLE ADDRESS;
DROP TABLE QUALIFICATION;
DROP TABLE PROJECT;
DROP TABLE GENERATED_ID;