
package jp.mufg.it.ee.ws.mtom;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MtomServicePortType", targetNamespace = "http://mtom.ws.ee.it.mufg.jp/")
@XmlSeeAlso({
    jp.mufg.it.ee.ws.mtom.ObjectFactory.class,
    org.w3._2005._05.xmlmime.ObjectFactory.class
})
public interface MtomServicePortType {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "byteTransfer", targetNamespace = "http://mtom.ws.ee.it.mufg.jp/", className = "jp.mufg.it.ee.ws.mtom.ByteTransfer")
    @ResponseWrapper(localName = "byteTransferResponse", targetNamespace = "http://mtom.ws.ee.it.mufg.jp/", className = "jp.mufg.it.ee.ws.mtom.ByteTransferResponse")
    @Action(input = "http://mtom.ws.ee.it.mufg.jp/MtomServicePortType/byteTransferRequest", output = "http://mtom.ws.ee.it.mufg.jp/MtomServicePortType/byteTransferResponse")
    public void byteTransfer(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "dataTransfer", targetNamespace = "http://mtom.ws.ee.it.mufg.jp/", className = "jp.mufg.it.ee.ws.mtom.DataTransfer")
    @ResponseWrapper(localName = "dataTransferResponse", targetNamespace = "http://mtom.ws.ee.it.mufg.jp/", className = "jp.mufg.it.ee.ws.mtom.DataTransferResponse")
    @Action(input = "http://mtom.ws.ee.it.mufg.jp/MtomServicePortType/dataTransferRequest", output = "http://mtom.ws.ee.it.mufg.jp/MtomServicePortType/dataTransferResponse")
    public void dataTransfer(
        @WebParam(name = "arg0", targetNamespace = "")
        DataHandler arg0);

}
