
package jp.mufg.it.ee.ws.mtom;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MtomService", targetNamespace = "http://mtom.ws.ee.it.mufg.jp/", wsdlLocation = "file:/D:/GitHubRepos/book_ap_archi_repo/20-06_ws_mtom_service_requestor/wsdl/MtomService.wsdl")
public class MtomService
    extends Service
{

    private final static URL MTOMSERVICE_WSDL_LOCATION;
    private final static WebServiceException MTOMSERVICE_EXCEPTION;
    private final static QName MTOMSERVICE_QNAME = new QName("http://mtom.ws.ee.it.mufg.jp/", "MtomService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/GitHubRepos/book_ap_archi_repo/20-06_ws_mtom_service_requestor/wsdl/MtomService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTOMSERVICE_WSDL_LOCATION = url;
        MTOMSERVICE_EXCEPTION = e;
    }

    public MtomService() {
        super(__getWsdlLocation(), MTOMSERVICE_QNAME);
    }

    public MtomService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MTOMSERVICE_QNAME, features);
    }

    public MtomService(URL wsdlLocation) {
        super(wsdlLocation, MTOMSERVICE_QNAME);
    }

    public MtomService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MTOMSERVICE_QNAME, features);
    }

    public MtomService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MtomService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MtomServicePortType
     */
    @WebEndpoint(name = "MtomServicePortTypePort")
    public MtomServicePortType getMtomServicePortTypePort() {
        return super.getPort(new QName("http://mtom.ws.ee.it.mufg.jp/", "MtomServicePortTypePort"), MtomServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MtomServicePortType
     */
    @WebEndpoint(name = "MtomServicePortTypePort")
    public MtomServicePortType getMtomServicePortTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mtom.ws.ee.it.mufg.jp/", "MtomServicePortTypePort"), MtomServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MTOMSERVICE_EXCEPTION!= null) {
            throw MTOMSERVICE_EXCEPTION;
        }
        return MTOMSERVICE_WSDL_LOCATION;
    }

}
