
package jp.mufg.it.ee.ws.hello;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloAsyncService", targetNamespace = "http://hello.ws.ee.it.mufg.jp/", wsdlLocation = "file:/D:/GitHubRepos/book_ap_archi_repo/20-06_ws_hello_async_service_requestor/wsdl/HelloAsyncService.wsdl")
public class HelloAsyncService
    extends Service
{

    private final static URL HELLOASYNCSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOASYNCSERVICE_EXCEPTION;
    private final static QName HELLOASYNCSERVICE_QNAME = new QName("http://hello.ws.ee.it.mufg.jp/", "HelloAsyncService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/GitHubRepos/book_ap_archi_repo/20-06_ws_hello_async_service_requestor/wsdl/HelloAsyncService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOASYNCSERVICE_WSDL_LOCATION = url;
        HELLOASYNCSERVICE_EXCEPTION = e;
    }

    public HelloAsyncService() {
        super(__getWsdlLocation(), HELLOASYNCSERVICE_QNAME);
    }

    public HelloAsyncService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOASYNCSERVICE_QNAME, features);
    }

    public HelloAsyncService(URL wsdlLocation) {
        super(wsdlLocation, HELLOASYNCSERVICE_QNAME);
    }

    public HelloAsyncService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOASYNCSERVICE_QNAME, features);
    }

    public HelloAsyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloAsyncService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloAsyncServicePortType
     */
    @WebEndpoint(name = "HelloAsyncServicePortTypePort")
    public HelloAsyncServicePortType getHelloAsyncServicePortTypePort() {
        return super.getPort(new QName("http://hello.ws.ee.it.mufg.jp/", "HelloAsyncServicePortTypePort"), HelloAsyncServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloAsyncServicePortType
     */
    @WebEndpoint(name = "HelloAsyncServicePortTypePort")
    public HelloAsyncServicePortType getHelloAsyncServicePortTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hello.ws.ee.it.mufg.jp/", "HelloAsyncServicePortTypePort"), HelloAsyncServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOASYNCSERVICE_EXCEPTION!= null) {
            throw HELLOASYNCSERVICE_EXCEPTION;
        }
        return HELLOASYNCSERVICE_WSDL_LOCATION;
    }

}
