-- 一括ドロップ
DROP TABLE FILE_STORE;

CREATE TABLE FILE_STORE (
FILE_ID      INT GENERATED BY DEFAULT AS IDENTITY, -- ファイルID
FILE_NAME    VARCHAR(200) NOT NULL,                -- ファイル名
CONTENT_TYPE VARCHAR(50) NOT NULL,                 -- コンテントタイプ
FILE         BLOB NOT NULL,                        -- ファイル
PRIMARY KEY (FILE_ID)
);
