
package jp.mufg.it.ee.ws.hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloFaultServicePortType", targetNamespace = "http://hello.ws.ee.it.mufg.jp/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloFaultServicePortType {


    /**
     * 
     * @throws BusinessException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "doBusiness", targetNamespace = "http://hello.ws.ee.it.mufg.jp/", className = "jp.mufg.it.ee.ws.hello.DoBusiness")
    @ResponseWrapper(localName = "doBusinessResponse", targetNamespace = "http://hello.ws.ee.it.mufg.jp/", className = "jp.mufg.it.ee.ws.hello.DoBusinessResponse")
    @Action(input = "http://hello.ws.ee.it.mufg.jp/HelloFaultServicePortType/doBusinessRequest", output = "http://hello.ws.ee.it.mufg.jp/HelloFaultServicePortType/doBusinessResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://hello.ws.ee.it.mufg.jp/HelloFaultServicePortType/doBusiness/Fault/BusinessException")
    })
    public void doBusiness()
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws FooException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://hello.ws.ee.it.mufg.jp/", className = "jp.mufg.it.ee.ws.hello.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://hello.ws.ee.it.mufg.jp/", className = "jp.mufg.it.ee.ws.hello.SayHelloResponse")
    @Action(input = "http://hello.ws.ee.it.mufg.jp/HelloFaultServicePortType/sayHelloRequest", output = "http://hello.ws.ee.it.mufg.jp/HelloFaultServicePortType/sayHelloResponse", fault = {
        @FaultAction(className = FooException_Exception.class, value = "http://hello.ws.ee.it.mufg.jp/HelloFaultServicePortType/sayHello/Fault/FooException")
    })
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws FooException_Exception
    ;

}
