SET sql_log_bin=OFF;
SET FOREIGN_KEY_CHECKS = 0;

USE DB_S;

TRUNCATE TABLE HISTORICAL_SALES_BY_CUSTOMER;
TRUNCATE TABLE HISTORICAL_SALES_BY_PRODUCT_TYPE;
TRUNCATE TABLE HISTORICAL_SALES_BY_PRODUCT;
TRUNCATE TABLE SALES_AMOUNT_BY_CUSTOMER;
TRUNCATE TABLE SALES_AMOUNT_BY_BRANCH;
TRUNCATE TABLE SALES_DETAIL;
TRUNCATE TABLE SALES_TRAN;
TRUNCATE TABLE STAFF;
TRUNCATE TABLE CUSTOMER;
TRUNCATE TABLE BRANCH;
TRUNCATE TABLE STOCK_PRODUCT;
TRUNCATE TABLE PRODUCT;
TRUNCATE TABLE PRODUCT_NEW_PRICE;
TRUNCATE TABLE PRODUCT_TYPE;

-- PRODUCT_TYPE
LOAD DATA LOCAL INFILE 'D:\\GitHubRepos\\book_ap_archi_repo\\16_06_java_batch_sales\\sql\\csv\\PRODUCT_TYPE.csv'
INTO TABLE PRODUCT_TYPE
FIELDS TERMINATED BY ','
(PRODUCT_TYPE_ID,PRODUCT_TYPE_NAME);

-- PRODUCT
LOAD DATA LOCAL INFILE 'D:\\GitHubRepos\\book_ap_archi_repo\\16_06_java_batch_sales\\sql\\csv\\PRODUCT.csv'
INTO TABLE PRODUCT
FIELDS TERMINATED BY ','
(PRODUCT_ID,PRODUCT_TYPE_ID,PRODUCT_NAME,PRICE);

-- PRODUCT_NEW_PRICE
LOAD DATA LOCAL INFILE 'D:\\GitHubRepos\\book_ap_archi_repo\\16_06_java_batch_sales\\sql\\csv\\PRODUCT_NEW_PRICE.csv'
INTO TABLE PRODUCT_NEW_PRICE
FIELDS TERMINATED BY ','
(PRODUCT_ID,NEW_PRICE);

-- STOCK_PRODUCT
LOAD DATA LOCAL INFILE 'D:\\GitHubRepos\\book_ap_archi_repo\\16_06_java_batch_sales\\sql\\csv\\STOCK_PRODUCT.csv'
INTO TABLE STOCK_PRODUCT
FIELDS TERMINATED BY ','
(PRODUCT_ID,QUANTITY);

-- BRANCH
LOAD DATA LOCAL INFILE 'D:\\GitHubRepos\\book_ap_archi_repo\\16_06_java_batch_sales\\sql\\csv\\BRANCH.csv'
INTO TABLE BRANCH
FIELDS TERMINATED BY ','
(BRANCH_ID,BRANCH_NAME);

-- STAFF
LOAD DATA LOCAL INFILE 'D:\\GitHubRepos\\book_ap_archi_repo\\16_06_java_batch_sales\\sql\\csv\\STAFF.csv'
INTO TABLE STAFF
FIELDS TERMINATED BY ','
(STAFF_ID,STAFF_NAME,BRANCH_ID);

-- CUSTOMER
LOAD DATA LOCAL INFILE 'D:\\GitHubRepos\\book_ap_archi_repo\\16_06_java_batch_sales\\sql\\csv\\CUSTOMER.csv'
INTO TABLE CUSTOMER
FIELDS TERMINATED BY ','
(BRANCH_ID,CUSTOMER_ID,CUSTOMER_NAME,EMAIL_ADDRESS,POSTAL_CODE,ADDRESS1,ADDRESS2);

-- SALES_TRAN
LOAD DATA LOCAL INFILE 'D:\\GitHubRepos\\book_ap_archi_repo\\16_06_java_batch_sales\\sql\\csv\\SALES_TRAN.csv'
INTO TABLE SALES_TRAN
FIELDS TERMINATED BY ','
(SALES_ID,SALES_DATE,DUE_DATE,BRANCH_ID,CUSTOMER_ID,STAFF_IN_CHARGE,UPDATE_STOCK_FLAG);

-- SALES_DETAIL
LOAD DATA LOCAL INFILE 'D:\\GitHubRepos\\book_ap_archi_repo\\16_06_java_batch_sales\\sql\\csv\\SALES_DETAIL.csv'
INTO TABLE SALES_DETAIL
FIELDS TERMINATED BY ','
(SALES_ID,SALES_DETAIL_ID,PRODUCT_ID,PRODUCT_PRICE,SALES_COUNT);
