-- 部署テーブル
CREATE TABLE DEPARTMENT (
DEPARTMENT_ID   INT PRIMARY KEY,      -- 部署ID
DEPARTMENT_NAME VARCHAR(30) NOT NULL, -- 部署名
LOCATION        VARCHAR(30) NOT NULL  -- 所在地
);

-- フルタイマーテーブル
CREATE TABLE FULLTIMER (
EMPLOYEE_ID   INT PRIMARY KEY,      -- 社員ID
EMPLOYEE_NAME VARCHAR(30) NOT NULL, -- 社員名
DEPARTMENT_ID INT,                   -- 部署ID
ENTRANCE_DATE DATE NOT NULL,        -- 入社年月日
JOB_ID      INT NOT NULL,           -- 役職ID
SALARY      INT NOT NULL,           -- 月給
CONSTRAINT FK_DEPARTMENT_1 FOREIGN KEY(DEPARTMENT_ID)
    REFERENCES DEPARTMENT(DEPARTMENT_ID)
);

-- パートタイマーテーブル
CREATE TABLE PARTTIMER (
EMPLOYEE_ID   INT PRIMARY KEY,      -- 社員ID
EMPLOYEE_NAME VARCHAR(30) NOT NULL, -- 社員名
DEPARTMENT_ID INT,                   -- 部署ID
ENTRANCE_DATE DATE NOT NULL,        -- 入社年月日
WAGE        INT NOT NULL,           -- 時給
CONSTRAINT FK_DEPARTMENT_2 FOREIGN KEY(DEPARTMENT_ID)
    REFERENCES DEPARTMENT(DEPARTMENT_ID)
);