
package jp.mufg.it.ee.ws.hello;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BusinessException", targetNamespace = "http://hello.ws.ee.it.mufg.jp/")
public class BusinessException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BusinessException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BusinessException_Exception(String message, BusinessException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BusinessException_Exception(String message, BusinessException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: jp.mufg.it.ee.ws.hello.BusinessException
     */
    public BusinessException getFaultInfo() {
        return faultInfo;
    }

}
