
package jp.mufg.it.ee.ws.hello;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloFaultService", targetNamespace = "http://hello.ws.ee.it.mufg.jp/", wsdlLocation = "file:/D:/GitHubRepos/book_ap_archi_repo/20-06_ws_fault_service_requestor/wsdl/HelloFaultService.wsdl")
public class HelloFaultService
    extends Service
{

    private final static URL HELLOFAULTSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOFAULTSERVICE_EXCEPTION;
    private final static QName HELLOFAULTSERVICE_QNAME = new QName("http://hello.ws.ee.it.mufg.jp/", "HelloFaultService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/GitHubRepos/book_ap_archi_repo/20-06_ws_fault_service_requestor/wsdl/HelloFaultService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOFAULTSERVICE_WSDL_LOCATION = url;
        HELLOFAULTSERVICE_EXCEPTION = e;
    }

    public HelloFaultService() {
        super(__getWsdlLocation(), HELLOFAULTSERVICE_QNAME);
    }

    public HelloFaultService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOFAULTSERVICE_QNAME, features);
    }

    public HelloFaultService(URL wsdlLocation) {
        super(wsdlLocation, HELLOFAULTSERVICE_QNAME);
    }

    public HelloFaultService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOFAULTSERVICE_QNAME, features);
    }

    public HelloFaultService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloFaultService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloFaultServicePortType
     */
    @WebEndpoint(name = "HelloFaultServicePortTypePort")
    public HelloFaultServicePortType getHelloFaultServicePortTypePort() {
        return super.getPort(new QName("http://hello.ws.ee.it.mufg.jp/", "HelloFaultServicePortTypePort"), HelloFaultServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloFaultServicePortType
     */
    @WebEndpoint(name = "HelloFaultServicePortTypePort")
    public HelloFaultServicePortType getHelloFaultServicePortTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hello.ws.ee.it.mufg.jp/", "HelloFaultServicePortTypePort"), HelloFaultServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOFAULTSERVICE_EXCEPTION!= null) {
            throw HELLOFAULTSERVICE_EXCEPTION;
        }
        return HELLOFAULTSERVICE_WSDL_LOCATION;
    }

}
