
package jp.mufg.it.ee.ws.hello;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapFaultExceptionService", targetNamespace = "http://hello.ws.ee.it.mufg.jp/", wsdlLocation = "file:/D:/GitHubRepos/book_ap_archi_repo/20-06_ws_fault_service_requestor/wsdl/SoapFaultExceptionService.wsdl")
public class SoapFaultExceptionService
    extends Service
{

    private final static URL SOAPFAULTEXCEPTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPFAULTEXCEPTIONSERVICE_EXCEPTION;
    private final static QName SOAPFAULTEXCEPTIONSERVICE_QNAME = new QName("http://hello.ws.ee.it.mufg.jp/", "SoapFaultExceptionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/GitHubRepos/book_ap_archi_repo/20-06_ws_fault_service_requestor/wsdl/SoapFaultExceptionService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPFAULTEXCEPTIONSERVICE_WSDL_LOCATION = url;
        SOAPFAULTEXCEPTIONSERVICE_EXCEPTION = e;
    }

    public SoapFaultExceptionService() {
        super(__getWsdlLocation(), SOAPFAULTEXCEPTIONSERVICE_QNAME);
    }

    public SoapFaultExceptionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPFAULTEXCEPTIONSERVICE_QNAME, features);
    }

    public SoapFaultExceptionService(URL wsdlLocation) {
        super(wsdlLocation, SOAPFAULTEXCEPTIONSERVICE_QNAME);
    }

    public SoapFaultExceptionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPFAULTEXCEPTIONSERVICE_QNAME, features);
    }

    public SoapFaultExceptionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapFaultExceptionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapFaultExceptionServicePortType
     */
    @WebEndpoint(name = "SoapFaultExceptionServicePortTypePort")
    public SoapFaultExceptionServicePortType getSoapFaultExceptionServicePortTypePort() {
        return super.getPort(new QName("http://hello.ws.ee.it.mufg.jp/", "SoapFaultExceptionServicePortTypePort"), SoapFaultExceptionServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapFaultExceptionServicePortType
     */
    @WebEndpoint(name = "SoapFaultExceptionServicePortTypePort")
    public SoapFaultExceptionServicePortType getSoapFaultExceptionServicePortTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hello.ws.ee.it.mufg.jp/", "SoapFaultExceptionServicePortTypePort"), SoapFaultExceptionServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPFAULTEXCEPTIONSERVICE_EXCEPTION!= null) {
            throw SOAPFAULTEXCEPTIONSERVICE_EXCEPTION;
        }
        return SOAPFAULTEXCEPTIONSERVICE_WSDL_LOCATION;
    }

}
