
package jp.mufg.it.ee.ws.hello;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloOnewayService", targetNamespace = "http://hello.ws.ee.it.mufg.jp/", wsdlLocation = "file:/D:/GitHubRepos/book_ap_archi_repo/20-06_ws_hello_oneway_service_requestor/wsdl/HelloOnewayService.wsdl")
public class HelloOnewayService
    extends Service
{

    private final static URL HELLOONEWAYSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOONEWAYSERVICE_EXCEPTION;
    private final static QName HELLOONEWAYSERVICE_QNAME = new QName("http://hello.ws.ee.it.mufg.jp/", "HelloOnewayService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/GitHubRepos/book_ap_archi_repo/20-06_ws_hello_oneway_service_requestor/wsdl/HelloOnewayService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOONEWAYSERVICE_WSDL_LOCATION = url;
        HELLOONEWAYSERVICE_EXCEPTION = e;
    }

    public HelloOnewayService() {
        super(__getWsdlLocation(), HELLOONEWAYSERVICE_QNAME);
    }

    public HelloOnewayService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOONEWAYSERVICE_QNAME, features);
    }

    public HelloOnewayService(URL wsdlLocation) {
        super(wsdlLocation, HELLOONEWAYSERVICE_QNAME);
    }

    public HelloOnewayService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOONEWAYSERVICE_QNAME, features);
    }

    public HelloOnewayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloOnewayService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloOnewayServicePortType
     */
    @WebEndpoint(name = "HelloOnewayServicePortTypePort")
    public HelloOnewayServicePortType getHelloOnewayServicePortTypePort() {
        return super.getPort(new QName("http://hello.ws.ee.it.mufg.jp/", "HelloOnewayServicePortTypePort"), HelloOnewayServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloOnewayServicePortType
     */
    @WebEndpoint(name = "HelloOnewayServicePortTypePort")
    public HelloOnewayServicePortType getHelloOnewayServicePortTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hello.ws.ee.it.mufg.jp/", "HelloOnewayServicePortTypePort"), HelloOnewayServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOONEWAYSERVICE_EXCEPTION!= null) {
            throw HELLOONEWAYSERVICE_EXCEPTION;
        }
        return HELLOONEWAYSERVICE_WSDL_LOCATION;
    }

}
